### ISSUE TITLE
updation of footer 

### ISSUE THREAD

**Issue by Madan2468** [ajaynegi45/upchaar-aayog#1]
hello @ajaynegi45 ,
Your footer is not professional as modern websites should be so I can update it , attaching an image below for the reference.
<img width="1253" alt="Screenshot 2024-09-29 at 11 07 03 PM" src="https://github.com/user-attachments/assets/d75693ce-7a38-454d-a94a-2a74d6f572d6">

**Comment by ajaynegi33** [comment]
> hello @ajaynegi45 , Your footer is not professional as modern websites should be so I can update it , attaching an image below for the reference. <img alt="Screenshot 2024-09-29 at 11 07 03 PM" width="1253" src="https://private-user-images.githubusercontent.com/114483527/372000603-d75693ce-7a38-454d-a94a-2a74d6f572d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MDAyMDIsIm5iZiI6MTcyNzY5OTkwMiwicGF0aCI6Ii8xMTQ0ODM1MjcvMzcyMDAwNjAzLWQ3NTY5M2NlLTdhMzgtNDU0ZC1hOTRhLTJhNzRkNmY1NzJkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQxMjM4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGE1YzYzMTAzNzA3MWQxZGQzODFmN2I4NDQxNDJjM2JkNzI0ZDYwNjRmNmFhNTlmNmE4YjE1ZGE4ZjY4MDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MLtfGZlvMZn2pneuZARwyshXdwIkXaK29jAcH4LjPYo">



Hi @Madan2468,

Thank you for expressing your interest in working on the "updation of footer" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project and work on "updation of footer" for the website is much appreciated.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out. We eagerly anticipate your work on creating an informative and visually appealing footer for our website. 

- **Make sure the footer color scheme matches the website's color scheme.**

**Comment by Madan2468** [comment]
sure kindly assign me this under Hacktoberfest 2024
