### ISSUE TITLE
Updation of header 

### ISSUE THREAD

**Issue by Madan2468** [ajaynegi45/upchaar-aayog#9]
hey @ajaynegi45 I would like to enhance the header by adding **animations** and making it modern by adding **hover effects**  . Adding my work for the reference below 
<img width="1372" alt="Screenshot 2024-10-03 at 9 05 06 PM" src="https://github.com/user-attachments/assets/05036b48-ea4a-4d8b-b582-cc1cec832fee">

<img width="1265" alt="Screenshot 2024-09-29 at 11 35 37 PM" src="https://github.com/user-attachments/assets/22be6276-aa8f-4817-bde9-a5fa9e0020fd">

**Comment by ajaynegi33** [comment]
> hey @ajaynegi45 I would like to enhance the header by adding **animations** and making it modern by adding **hover effects** . Adding my work for the reference below <img alt="Screenshot 2024-10-03 at 9 05 06 PM" width="1372" src="https://private-user-images.githubusercontent.com/114483527/373318181-05036b48-ea4a-4d8b-b582-cc1cec832fee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NzMzNDksIm5iZiI6MTcyNzk3MzA0OSwicGF0aCI6Ii8xMTQ0ODM1MjcvMzczMzE4MTgxLTA1MDM2YjQ4LWVhNGEtNGQ4Yi1iNTgyLWNjMWNlYzgzMmZlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNjMwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGVkMGI2MmY0NTc4NWM1MGM5OGMwYWY5OTUzNWU2NGU0NzU1NTM5ODIzZTlkNjQ1ZmZhN2U1YmJkNzQwZGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MR9e3i9pg3IGqmfLnpUVjpk0pB8pR6BBds66DmIRaiI">
> 
> <img alt="Screenshot 2024-09-29 at 11 35 37 PM" width="1265" src="https://private-user-images.githubusercontent.com/114483527/373318592-22be6276-aa8f-4817-bde9-a5fa9e0020fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NzMzNDksIm5iZiI6MTcyNzk3MzA0OSwicGF0aCI6Ii8xMTQ0ODM1MjcvMzczMzE4NTkyLTIyYmU2Mjc2LWFhOGYtNDgxNy1iZGU5LWE1ZmE5ZTAwMjBmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNjMwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2E0NTM3NjBkNTVjOTUwM2MwOWVkZTIyZjhmYWYxYzY3MWU5ZDdjMzVkMTNmOGU4MmFlNDUzNGU0MTE3MzdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mb_9dxb9YlepJ383wRVyd17w1J2CuudS-dEe-g_w2iM">

Hi @Madan2468,

Thank you for expressing your interest in working on this issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.
